version: '3'
services:
    postgresdb:
      image: postgres:latest
      volumes:
        - ./postgres-data:/var/lib/postgresql
      environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
        POSTGRES_DB: apateez
      ports:
        - "5432:5432"